import { tryGetActiveLanguage } from "./active-language";

/**
 * Returns the URL of a pre-generated MP3 for `text`, or null if none exists.
 * Pre-generated audio is the highest-quality tier — recorded once with
 * ElevenLabs (or another provider) and served as static files.
 *
 * The manifest now lives on the active language module rather than as a
 * single global import, so each learning language can ship its own audio.
 */
export function lookupAudio(text: string): string | null {
  const lang = tryGetActiveLanguage();
  if (!lang) return null;
  const key = text.trim();
  const hash = lang.audioManifest[key];
  if (!hash) return null;
  // Audio MP3s live under /public/audio/{language-code}/{hash}.mp3 so that
  // adding a second language can't collide with Romanian's hashes — every
  // language ships its own folder, generated by `npm run generate-audio`.
  return `${import.meta.env.BASE_URL}audio/${lang.code}/${hash}.mp3`;
}

export function hasPreGeneratedAudio(text: string): boolean {
  const lang = tryGetActiveLanguage();
  if (!lang) return false;
  return lang.audioManifest[text.trim()] !== undefined;
}
